// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateJob(arg1) {
  return window['go']['services']['JobService']['CreateJob'](arg1);
}

export function DeleteAllHistory() {
  return window['go']['services']['JobService']['DeleteAllHistory']();
}

export function DeleteAllJobHistory(arg1) {
  return window['go']['services']['JobService']['DeleteAllJobHistory'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['services']['JobService']['DeleteHistory'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['services']['JobService']['DeleteJob'](arg1);
}

export function DeleteJobHistory(arg1) {
  return window['go']['services']['JobService']['DeleteJobHistory'](arg1);
}

export function DuplicateJob(arg1) {
  return window['go']['services']['JobService']['DuplicateJob'](arg1);
}

export function ExportJobs(arg1) {
  return window['go']['services']['JobService']['ExportJobs'](arg1);
}

export function GetHistory(arg1, arg2) {
  return window['go']['services']['JobService']['GetHistory'](arg1, arg2);
}

export function GetJobByID(arg1) {
  return window['go']['services']['JobService']['GetJobByID'](arg1);
}

export function GetJobHistory(arg1, arg2) {
  return window['go']['services']['JobService']['GetJobHistory'](arg1, arg2);
}

export function GetJobHistoryPage(arg1, arg2, arg3) {
  return window['go']['services']['JobService']['GetJobHistoryPage'](arg1, arg2, arg3);
}

export function GetJobs() {
  return window['go']['services']['JobService']['GetJobs']();
}

export function ImportJobs(arg1) {
  return window['go']['services']['JobService']['ImportJobs'](arg1);
}

export function PauseJob(arg1) {
  return window['go']['services']['JobService']['PauseJob'](arg1);
}

export function ResumeJob(arg1) {
  return window['go']['services']['JobService']['ResumeJob'](arg1);
}

export function SetScheduler(arg1) {
  return window['go']['services']['JobService']['SetScheduler'](arg1);
}

export function TriggerJob(arg1) {
  return window['go']['services']['JobService']['TriggerJob'](arg1);
}

export function UpdateJob(arg1) {
  return window['go']['services']['JobService']['UpdateJob'](arg1);
}
