// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function CreateJob(arg1:models.Job):Promise<models.Job>;

export function DeleteAllHistory():Promise<void>;

export function DeleteAllJobHistory(arg1:string):Promise<void>;

export function DeleteHistory(arg1:string):Promise<void>;

export function DeleteJob(arg1:string):Promise<void>;

export function DeleteJobHistory(arg1:string):Promise<void>;

export function DuplicateJob(arg1:string):Promise<models.Job>;

export function ExportJobs(arg1:string):Promise<void>;

export function GetHistory(arg1:any,arg2:boolean):Promise<Array<models.History>>;

export function GetJobByID(arg1:string):Promise<models.Job>;

export function GetJobHistory(arg1:string,arg2:number):Promise<Array<models.History>>;

export function GetJobHistoryPage(arg1:string,arg2:number,arg3:number):Promise<Array<models.History>>;

export function GetJobs():Promise<Array<models.Job>>;

export function ImportJobs(arg1:string):Promise<void>;

export function PauseJob(arg1:string):Promise<void>;

export function ResumeJob(arg1:string):Promise<void>;

export function SetScheduler(arg1:services.Scheduler):Promise<void>;

export function TriggerJob(arg1:string):Promise<void>;

export function UpdateJob(arg1:models.Job):Promise<models.Job>;
