// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckImportFileHasDefaults(arg1:string):Promise<boolean>;

export function ExportJobsWithDialog():Promise<void>;

export function GetDefaults():Promise<models.Defaults>;

export function Greet(arg1:string):Promise<string>;

export function ImportJobsFromFile(arg1:string):Promise<void>;

export function ImportJobsWithDialog():Promise<void>;

export function PrepareImportWithDialog():Promise<Record<string, any>>;

export function TriggerJob(arg1:string):Promise<void>;

export function UpdateDefaults(arg1:models.Defaults):Promise<models.Defaults>;
