// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckImportFileHasDefaults(arg1) {
  return window['go']['main']['App']['CheckImportFileHasDefaults'](arg1);
}

export function ExportJobsWithDialog() {
  return window['go']['main']['App']['ExportJobsWithDialog']();
}

export function GetDefaults() {
  return window['go']['main']['App']['GetDefaults']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportJobsFromFile(arg1) {
  return window['go']['main']['App']['ImportJobsFromFile'](arg1);
}

export function ImportJobsWithDialog() {
  return window['go']['main']['App']['ImportJobsWithDialog']();
}

export function PrepareImportWithDialog() {
  return window['go']['main']['App']['PrepareImportWithDialog']();
}

export function TriggerJob(arg1) {
  return window['go']['main']['App']['TriggerJob'](arg1);
}

export function UpdateDefaults(arg1) {
  return window['go']['main']['App']['UpdateDefaults'](arg1);
}
